openapi: "3.0.1"
info:
  title: NBRB API
  description: NBRB API.
  version: "1.0.0"
servers:
  - url: https://api.nbrb.by/
    description: NBRB production API.
  - url: https://sandbox.nbrb.by/
    description: Sandbox API.
paths:
  /banks:
    get:
      summary: Banks
      description: Bank.
      tags:
        - Public
      parameters:
        - $ref: '#/components/parameters/AcceptParameter'
        - $ref: '#/components/parameters/ContentTypeParameter'
        - $ref: '#/components/parameters/ApiVersionParameter'
        - $ref: '#/components/parameters/LocalisationParameter'
      responses:
        '200':
          description: An array of banks.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankList"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /currencies:
    get:
      summary: Currencies
      description: Currencies.
      tags:
        - Public
      parameters:
        - $ref: '#/components/parameters/AcceptParameter'
        - $ref: '#/components/parameters/ContentTypeParameter'
        - $ref: '#/components/parameters/ApiVersionParameter'
        - $ref: '#/components/parameters/LocalisationParameter'
        - name: at
          in: query
          description: Currancy rate at specific date. Current time used by default.
          required: false
          schema:
            type: dateTime
      responses:
        '200':
          description: An array of currencies.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CurrencyRateList"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    PostalAddress:
      properties:
        country:
          type: string
          format: iso-3166-1
          description: Country code.
          example: "BY"
        state:
          type: string
          description: State (localisation).
          example: "Minsk"
        city:
          type: string
          description: City (localisation).
          example: "Minsk"
        line:
          type: string
          description: Address (localisation).
          example: "praspiekt Niezaliežnasci, 20"
        postcode:
          type: string
          description: Postcode.
          example: "220008"
      required:
        - country
        - state
        - city
        - line
    Bank:
      properties:
        type:
          type: string
          description: Type `Bank`.
          example: "Bank"
        handle:
          type: string
          description: Unique identifier of bank.
          example: "nbrb"
        name:
          type: string
          description: Short bank name (localisation).
          example: "NBRB"
        full_name:
          type: string
          description: Full bank name (localisation).
          example: "National Bank of the Republic of Belarus"
        bic:
          type: string
          description: Bank BIC
          example: "IRJSBY22"
        unp:
          type: string
          description: Bank UNP
        okpo:
          type: string
          description: Bank OKPO
        swift:
          type: string
          description: Bank S.W.I.F.T.
          example: "NBRB BY2X"
        address:
          $ref: "#/components/schemas/PostalAddress"
          description: Bank address (localisation).
        phone:
          type: string
          format: phone
          description: Bank phone.
          example: "+375173060002"
        fax:
          type: string
          format: phone
          description: Bank fax.
          example: "+375173274879"
        telex:
          type: string
          description: Bank telex.
          example: "252449 BELAR BY"
        email:
          type: string
          format: email
          description: Bank email.
          example: "info@nbrb.by"
        website:
          type: string
          format: uri
          description: Bank web site (localisation).
          example: "https://nbrb.by/"
        presedent:
          type: string
          description: Bank president (localisation).
        registration_number:
          type: string
          description: Registration number.
          example: "1"
        registration_date:
          type: date
          description: Registration date.
          example: "1991-01-01"
    BankList:
      properties:
        items:
          description: Contains the list of banks.
          type: array
          items:
            $ref: "#/components/schemas/Bank"
    CurrencyRate:
      properties:
        type:
          type: string
          description: Type `CurrencyRate`.
          example: "CurrencyRate"
        currency_from:
          type: string
          format: iso-4217
          description: Currency ISO 4217 code.
          example: "EUR"
        currency_from_name:
          type: string
          description: Currency name (localisation).
          example: "Euro"
        currency_to:
          type: string
          format: iso-4217
          description: Currency ISO 4217 code.
          example: "BYN"
        currency_to_name:
          type: string
          description: Currency name (localisation).
          example: "Belarusian ruble"
        exchange_rate:
          type: string
          format: decimal
          description: Currency echange rate.
          example: "2.3676"
    CurrencyRateList:
      properties:
        items:
          description:  Contains the list of currencies.
          type: array
          items:
            $ref: "#/components/schemas/CurrencyRate"
    Error:
      properties:
        code:
          type: string
        message:
          type: string
        fields:
          type: string
  parameters:
    AcceptParameter:
      name: Accept
      in: header
      description: Accept response body content type (default application/json).
      required: false
      schema:
        type: string
        enum:
          - application/json
    ContentTypeParameter:
      name: Content-Type
      in: header
      description: Request body content type (default application/json).
      required: false
      schema:
        type: string
        enum:
          - application/json
    ApiVersionParameter:
      name: X-Api-Version
      in: header
      description: API version (default latest).
      required: false
      schema:
        type: string
        example: 1.0.0
    LocalisationParameter:
      name: lang
      in: query
      description: Language of text data (default belarusan).
      required: false
      schema:
        type: string
        format: iso-639-1
        enum:
          - be
          - ru
          - en-US
        example: be
